### ISSUE TITLE
Cannot find symbol for Custom app React symbols

### ISSUE THREAD

**Issue by MissShuwa** [khanhas/spicetify-cli#897] opened 2021-07-14 07:45 UTC
Got on the newst Version Cannot find symbol for Custom app React symbols

**Comment by Davoleo** [comment] 2021-07-14 07:59
Duplicate of #845

**Closed** 2021-07-14 20:45 UTC
Labels: bug

**Comment by afonsojramos** [comment] 2021-07-14 20:46
@MissShuwa Next time please research the issue first, and afterwards, please provide more information on it so that someone can understand it and fix it.
