### ISSUE TITLE
New version of spotify breaks spiceitfy 2.8.3

### ISSUE THREAD

**Issue by CryoRenegade** [khanhas/spicetify-cli#1361] opened 2021-12-11 06:21 UTC
## ℹ Computer information

- Spotify version: 1.1.74.631.g0b24d9ad
- Spicetify version: 2.8.3

## 📝 Provide detailed reproduction steps (if any)

1. `spicetify backup apply`

### ✔️ Expected result
Spotify Loads the correct CSS and JS plugins
_What is the expected result of the above steps?_

### ❌ Actual result
![image](https://user-images.githubusercontent.com/23038070/145666592-91e03cdd-b3f3-4e8c-a9c5-22c96af76e05.png)

_What is the actual result of the above steps?_
Spotify doesn't load correctly

**Comment by jakublevy** [comment] 2021-12-11 07:04
duplicate of #1344

**Closed** 2021-12-11 07:08 UTC
Labels: bug
