### ISSUE TITLE
Nothings loading.

### ISSUE THREAD

**Issue by berryes** [khanhas/spicetify-cli#929] opened 2021-07-27 11:40 UTC
## ℹ Computer information

- Spotify version: 1.1.64.561.g71bd09eb
- Spicetify version:  2.5.0

This has been like this for a week. No idea why
![image](https://user-images.githubusercontent.com/73071529/127147682-aca1e676-e345-4729-998c-528004603bcd.png)

**Comment by ricozyx** [comment] 2021-07-27 12:03
Duplicate of: https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-880459337

**Comment by itsmeow** [comment] 2021-08-06 00:08
Patch available: #945 https://github.com/itsmeowForks/spicetify-cli/releases/tag/v2.5.0-patch2

**Comment by afonsojramos** [comment] 2021-08-17 17:39
Please update to v2.6.0 and retry, thanks!

**Closed by afonsojramos** 2021-08-17 17:39 UTC
Labels: bug
