### ISSUE TITLE
Spicetify does not seem to work with spotify 1.1.56?

### ISSUE THREAD

**Issue by Username404-59** [khanhas/spicetify-cli#941] opened 2021-07-31 21:58 UTC
## ℹ Computer information

- Spotify version: 1.1.56.595.g2d2da0de
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. Install spicetify
2. Add a theme (https://github.com/morpheusthewhite/spicetify-themes/tree/master/Sleek with the Deep color scheme in my case) and apply

### ✔️ Expected result

Working spotify with a theme

### ❌ Actual result

A colored page

## 📷 Screenshots

![brokespotify](https://user-images.githubusercontent.com/53659497/127753275-00afeb69-7e04-41fd-8e08-cc4a4da4f6c4.png)

**Comment by Username404-59** [comment] 2021-07-31 22:55
Is spicetify 2.5.0 meant to work with this version of spotify?

**Comment by VarChar42** [comment] 2021-08-01 12:50
Duplicate of #845.
https://github.com/khanhas/spicetify-cli/issues/845#issuecomment-880459337 might help.

**Comment by afonsojramos** [comment] 2021-08-01 13:46
@Username404-59 this is due to the fact that Spotify has not updated their version on Linux to match the other versions on other OSs. To fix this just install Spicetify v1 which can be found here: https://github.com/khanhas/spicetify-cli/wiki/Installation#linux-legacy-spotify

**Closed** 2021-08-01 13:47 UTC
Labels: bug

**Comment by Username404-59** [comment] 2021-08-01 21:30
I thought that spicetify v2 could work because this release: https://github.com/khanhas/spicetify-cli/releases/tag/v2.1.0 says that spotify 1.1.56 is supported
