### ISSUE TITLE
Lyrics Plus not loading

### ISSUE THREAD

**Issue by gunacorn** [khanhas/spicetify-cli#980] opened 2021-08-18 22:01 UTC
Starting this off with not the most experienced, but I followed the instructions to enable lyrics plus but every time I click on the tab to open it it just says something went wrong, and the option to reload the page. I don't know if this is a bug or if this is my own fault. Could someone please let me know if I did something wrong or if this is a bug?
![image](https://user-images.githubusercontent.com/62181389/129977888-3d602fbc-d835-4df5-8d4d-78812ae76272.png)

**Comment by gunacorn** [comment] 2021-08-18 22:03
I apologise, as I forgot to update my spicetify.

**Comment by TerraDK** [comment] 2021-09-01 07:38
with 2.6.1 this is happening to me as well. fresh install.

**Comment by afonsojramos** [comment] 2021-09-01 09:46
@TerraDK you are correct, I'll reopen this issue so that future people know this is happening even though it is probably related to CSS mappings.

**Comment by devilAPI** [comment] 2021-09-02 01:27
Same Issue, using 2.6.1

**Comment by devilAPI** [comment] 2021-09-02 01:28
Reddit Plugin is also broken, i noticed

**Comment by CharlieS1103** [comment] 2021-09-02 01:43
Yeah we're working on fixing it atm, it's just due to css mapping being fucked and it will be solved soon enough.

**Comment by afonsojramos** [comment] 2021-09-21 02:50
Will continue tracking at #1062. Duplicate of #1062.

**Closed by afonsojramos** 2021-09-21 02:50 UTC
Labels: bug
