### ISSUE TITLE
Only 4 buttons show up.

### ISSUE THREAD

**Issue by yyovanyovo** [khanhas/spicetify-cli#900] opened 2021-07-15 16:33 UTC
## ℹ Computer information

- Spotify version: 1.1.63.568.gda8cb5ac-a
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. run spicetify
2. run spicetify backup apply
3. spotify restarts, only the top left three dots on the top left, the minimize, maximize and close buttons are visible.

### ✔️ Expected result

Spotify appearing as usual.

### ❌ Actual result

Only 4 buttons show up. Need to run spicetify restore to go back to normal so spotify is usable, but obviously then I don't have spicetify active.

## 📷 Screenshots

![image1](https://user-images.githubusercontent.com/80846437/125824294-37058181-f5dd-4f48-981f-8a173661b085.JPG)
![image2](https://user-images.githubusercontent.com/80846437/125824297-eb22d4b3-a3f2-43f4-87c5-8894a5b78b64.JPG)

**Comment by afonsojramos** [comment] 2021-07-15 16:35
Duplicate of #845

**Closed by afonsojramos** 2021-07-15 16:35 UTC
Labels: bug
