### ISSUE TITLE
Spicetify upgrade error

### ISSUE THREAD

**Issue by sn4dy** [khanhas/spicetify-cli#978] opened 2021-08-18 14:27 UTC
## ℹ Computer information

- Spotify version: Spotify version 1.1.55.498.gf9a83c60, Copyright (c) 2021, Spotify Ltd
- Spicetify version: 2.5.0-itsmeow-patch4

## 📝 Provide detailed reproduction steps (if any)

1. spicetify upgrade
2. spicetify restore backup apply

## 📷 Screenshots

`sn4dy@sn4dy-ubuntu ~ spicetify upgrade                                                                    
Fetch latest release info:
OK
info Current version: 2.5.0-itsmeow-patch4
info Latest release: 2.6.0
Downloading:
OK
Extracting:
OK
success spicetify is up-to-date.
info Please run "spicetify restore backup apply" to receive new features and bug fixes
 sn4dy@sn4dy-ubuntu  ~  spicetify restore backup apply
spicetify v2.5.0-itsmeow-patch4
success Spotify is restored.
info There is available backup.
info Clear current backup:
success Backup is cleared.
Backing up app files:
OK
Extracting:
OK
Preprocessing:
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc001452000, 0x12ee90, 0x12ee90, 0xc001452000)
	C:/Users/itsmeow/spicetify-cli/spicetify-cli/src/apply/apply.go:180 +0xd86
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc000e87c80, 0x24, 0xc0000939d8)
	C:/Users/itsmeow/spicetify-cli/spicetify-cli/src/utils/utils.go:190 +0xd8
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc000e87c80, 0x24, 0xc000096520, 0x1, 0x2, 0xc000096540, 0x1, 0x2, 0x101)
	C:/Users/itsmeow/spicetify-cli/spicetify-cli/src/apply/apply.go:155 +0x97
github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc0000e41f8, 0x17, 0xc000096520, 0x1, 0x2, 0xc000096540, 0x1, 0x2, 0x101)
	C:/Users/itsmeow/spicetify-cli/spicetify-cli/src/apply/apply.go:34 +0x466
github.com/khanhas/spicetify-cli/src/cmd.Apply(0x7a9fe0, 0x14)
	C:/Users/itsmeow/spicetify-cli/spicetify-cli/src/cmd/apply.go:73 +0x58c
main.main()
	C:/Users/itsmeow/spicetify-cli/spicetify-cli/spicetify.go:189 +0x4f9`

**Comment by edo2313** [comment] 2021-08-19 01:03
Duplicate of #845

**Closed** 2021-08-22 07:58 UTC
Labels: bug
