### ISSUE TITLE
Something went wrong

### ISSUE THREAD

**Issue by glisteningcoder** [khanhas/spicetify-cli#1257] opened 2021-11-12 04:56 UTC
## ℹ Computer information

- Spotify version: 1.1.72.439
- Spicetify version: 2.8.0

## 📝 Provide detailed reproduction steps (if any)

1. I installed the newest version of Spotify and reapplied Spicetify

### ✔️ Expected result

_What is the expected result of the above steps?_
It should show the main page without any error.

### ❌ Actual result

_What is the actual result of the above steps?_
This window
## 📷 Screenshots
![image](https://user-images.githubusercontent.com/66782694/141412026-9da50e6c-a4bd-4d84-8c12-5808158bba06.png)

**Comment by Ddangkri** [comment] 2021-11-12 05:30
I have the same issue in my computer. Attaching error message from Devtools:
![image](https://user-images.githubusercontent.com/94158860/141414847-155099e9-3d7c-46ca-bed2-66bef17871a3.png)
It goes alright when I reinstall Spotify and apply Spicetify, but it goes wrong when I apply 'custom apps' or etc. Solutions? (I'm literally finding the solutions for over a half day, but I couldn't)

**Comment by pWoLiAn** [comment] 2021-11-12 06:11
me too.running v2.8.0 on windows 11

**Comment by mizzunet** [comment] 2021-11-12 07:16
Us this similar to https://github.com/khanhas/spicetify-cli/issues/1258? Have you installed LyricsPlus?

**Comment by Ddangkri** [comment] 2021-11-12 07:30
Yes, I was using lyrics-plus so I removed it: but it's strange that the error doesn't only apply to lyrics-plus. Also with changing themes, extensions, and more.

**Comment by pWoLiAn** [comment] 2021-11-12 07:31
yes lyrics plus was installed.I removed it and it went back to normal but now the extensions stopped working

**Comment by mizzunet** [comment] 2021-11-12 07:32
@mizzunet I have installed extensions fullAppDisplay.js and keyboardShortcut.js and SpotifyNoPremium as then, that's all. No issue now

**Comment by TheGeeKing** [comment] 2021-11-12 07:35
Duplicate of #1249

**Comment by Ddangkri** [comment] 2021-11-12 07:46
yeah, I think my CSS mappings got broken and really want to update them with https://github.com/itsmeow/spicetify-css-remapper
but I don't know how to apply it...(there are steps mentioned, but donno to apply it)

**Comment by TheGeeKing** [comment] 2021-11-12 07:48
Don't use it. It is not meant to be use by users. Just delete and reinstall Spicetify.

**Comment by Ddangkri** [comment] 2021-11-12 07:50
okay. I'll reinstall them and reply again.

**Comment by Ddangkri** [comment] 2021-11-12 08:14
Umm.. Still same. What should I do? (I used the code in powershell with Administrator mode)
`cd ~
rm -r spicetify-cli
rm -r .spicetify
Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.ps1" | Invoke-Expression`

**Comment by Ddangkri** [comment] 2021-11-12 08:54
I uninstalled Spotify and Spicetify, and reinstalled both of 'em. And, I justed added an extension popupLyrics.js and there is no issue now. I think lyrics-plus is the problem as other mentioned. Thks!

**Comment by itsmeow** [comment] 2021-11-12 17:53
Anyone w this issue, reinstall Spotify, run `spicetify backup apply`. DO NOT RESTORE. Ensure using 2.8.0.

**Closed by itsmeow** 2021-11-12 17:54 UTC
Labels: bug

**Comment by khanhas** [comment] 2021-11-13 03:07
Upgrade v2.8.1 and it should work now.
