### ISSUE TITLE
Upgrading spicetify to 2.7.1 through brew switches it to vDev

### ISSUE THREAD

**Issue by lor1x** [khanhas/spicetify-cli#1169] opened 2021-10-15 16:04 UTC
## ℹ Computer information

- Spotify version: 1.1.70.610.g4585142b
- Spicetify version: 2.7.1

## 📝 Provide detailed reproduction steps (if any)

1. Run brew upgrade

### ✔️ Expected result

Spicetify updates normally as usual

### ❌ Actual result

Upgrading through brew switches to the spicetify vDev

**Comment by ririxidev** [comment] 2021-10-15 16:29
Will look into it later

**Comment by lor1x** [comment] 2021-10-15 16:38
Yup I know, just that it created another spicetify_data folder that I couldn’t find at first. It was on $HOME/.config/spicetify so I just replaced the config file with the one I had at spicetify_data and applied the changes.

**Comment by lor1x** [comment] 2021-10-15 16:46
Yes this is where it gets installed by brew `/usr/local/Cellar/spicetify-cli/`.
I thought that change to `spicetify_data` location was a side effect of spicetify being vDev but it seems that this is going to be the new default

**Comment by afonsojramos** [comment] 2021-10-15 17:58
> .

@ririxidev i did? Are you sure?

**Comment by itsmeow** [comment] 2021-10-15 18:01
Nope, brew doesn't have the version command line argument in the buildscript.

**Comment by itsmeow** [comment] 2021-10-15 19:03
Can someone downgrade and test it now?

**Comment by lor1x** [comment] 2021-10-15 20:04
@itsmeow Here you go:
![Screen Shot 2021-10-15 at 22 04 16](https://user-images.githubusercontent.com/22913459/137547089-a3a73c2b-3b60-4155-a8fe-ba00c8ba425f.png)

**Comment by itsmeow** [comment] 2021-10-15 20:06
`ls -al /usr/local/bin | grep spicetify`?
Might be a symlink?

**Comment by itsmeow** [comment] 2021-11-02 22:35
@afonsojramos Label: "help wanted"

**Comment by afonsojramos** [comment] 2021-11-02 22:43
Yeah.... I'm at WebSummit this week, but ill try to remote it to my machine and do a release even today, sorry guys!!

**Comment by TheGeeKing** [comment] 2021-11-07 00:01
any update @ririxidev @itsmeow @afonsojramos ?

**Comment by itsmeow** [comment] 2021-11-07 01:27
This issue isn't something I know how to resolve, so it's just going to stay open until someone who knows what they're doing with AUR or homebrew comes by.

**Comment by afonsojramos** [comment] 2021-11-07 23:02
Is this even an issue on the new version @itsmeow ?

**Comment by GameFuzzy** [comment] 2021-11-10 19:23
> This issue isn't something I know how to resolve, so it's just going to stay open until someone who knows what they're doing with AUR or homebrew comes by.

Don’t think it has anything to do with the AUR or Homebrew. From what I can tell the binaries are just downloaded straight from the releases page. Are you sure the ldflags are actually being set correctly?

**Comment by itsmeow** [comment] 2021-11-10 19:29
@GameFuzzy AUR and Homebrew build Spicetify from scratch as far as I know. The releases downloads have the correct versions.

**Comment by GameFuzzy** [comment] 2021-11-10 20:24
> @GameFuzzy AUR and Homebrew build Spicetify from scratch as far as I know. The releases downloads have the correct versions.

@itsmeow Oh yeah my bad. You're absolutely correct. Seems I just skimmed through without paying any attention. Anyway, I'll try to see if I can whip up something that works for the PKGBUILD.

**Comment by GameFuzzy** [comment] 2021-11-10 22:18
Changing line 16 of the PKGBUILD to:
 `go build -ldflags="-X 'main.version=$pkgver'" -o spicetify` 
seems to be enough to get it to work on Arch.

I took a look at the Homebrew tap and I believe the issue is that it's missing both the equal sign after `-ldflags` and the single quotes surrounding `main.version=<version>`. 
To fix this I'd change line 13 to:
`system "go", "build", %Q[-ldflags="-X 'main.version=#{version.to_s}'"], "-o", "spicetify"`
Someone other than me would have to test to see if this actually works though.

**Comment by itsmeow** [comment] 2021-11-10 22:27
Committed the changes. @lor1x Can you try reinstalling?

**Comment by lor1x** [comment] 2021-11-10 22:28
On it @itsmeow, will edit this post once I’m done

**Comment by itsmeow** [comment] 2021-11-10 22:32
Changes on AUR added @GameFuzzy, confirm fix?

**Comment by GameFuzzy** [comment] 2021-11-10 22:37
The issue has been fixed for the AUR package.

**Comment by GameFuzzy** [comment] 2021-11-10 22:50
My guess here would be that the MacOS issue is still present because the GOPATH is not set to where the main package is.

**Comment by ririxidev** [comment] 2021-11-12 17:51
Made pull request on homebrew-tap repo to fix it. Everything will work fine now, @lor1x https://github.com/khanhas/homebrew-tap/pull/10

**Closed** 2021-11-12 17:57 UTC
Labels: bug, help wanted, brew

**Comment by ririxidev** [comment] 2021-11-12 18:07
> My guess here would be that the MacOS issue is still present because the GOPATH is not set to where the main package is.

@GameFuzzy I'm also wondering how it has been fixed, when ldflags are used not in the way that they should.
You are trying to pass `=` to ldflags, and it shouldn't be a thing here.
Proper command is; for example;
`go build -ldflags "-X main.version=2.8.0" -o spicetify`
This is proper way of using ldflags in `go build`.

**Comment by lor1x** [comment] 2021-11-13 11:11
Thank you!

**Comment by GameFuzzy** [comment] 2021-11-13 16:54
> > My guess here would be that the MacOS issue is still present because the GOPATH is not set to where the main package is.
> 
> @GameFuzzy I'm also wondering how it has been fixed, when ldflags are used not in the way that they should. You are trying to pass `=` to ldflags, and it shouldn't be a thing here. Proper command is; for example; `go build -ldflags "-X main.version=2.8.0" -o spicetify` or `go build -ldflags -X main.version=2.8.0 -o spicetify` This is proper way of using ldflags in `go build`. but maybe it depends on system 🤷

@ririxidev 
According to JetBrains `ldflags=""` is the "proper way" to do it: https://blog.jetbrains.com/go/2019/02/06/debugging-with-goland-getting-started/
I just used the syntax I saw most frequently when I looked it up. Fairly sure they’re synonymous.

**Comment by ririxidev** [comment] 2021-11-13 18:54
Hmm, okay, but that's weird tho, because when I was actually building with `ldflags="-X [...]"` it didn't do it properly. When I switched script to `ldflags -X` it worked perfectly fine
🤔
