### ISSUE TITLE
Can't Add Custom Apps 

### ISSUE THREAD

**Issue by DawnAura** [khanhas/spicetify-cli#966] opened 2021-08-16 05:49 UTC
Hello!
I got Spicetify a week ago, and I didn't get around to applying anything at the time. So, today, I decided to apply the webnowplaying.js plugin and the lyrics-plus custom app, but when I use the command 'spicetify apply' I get the following error:
![Screenshot (950)](https://user-images.githubusercontent.com/89002405/129516989-09518e03-078d-47e9-9ac2-265f2aa6bf93.png)
Help would be appreciated, ty <3

**Comment by itsmeow** [comment] 2021-08-17 01:46
Duplicate of #845, Patch available see #945

**Closed** 2021-08-17 03:03 UTC
Labels: bug
