### ISSUE TITLE
can't upgrade to 2.6.0, stuck on 2.5.0-itsmeow-patch4

### ISSUE THREAD

**Issue by UltimateLight** [khanhas/spicetify-cli#979] opened 2021-08-18 14:56 UTC
## ℹ Computer information

- Spotify version: 1.1.66.578.gc54d0f69-a
- Spicetify version: 2.5.0-itsmeow-patch4

## 📝 Provide detailed reproduction steps (if any)

try upgrading spicetify to latest version

### ✔️ Expected result

upgrade to 2.6.0 without any problems

### ❌ Actual result

stuck on 2.5.0-itsmeow-patch4

## 📷 Screenshots

![Screenshot_50](https://user-images.githubusercontent.com/63460105/129921237-766e7a68-3743-4bbf-a076-ba0e70fe59a6.png)

**Comment by edo2313** [comment] 2021-08-18 16:49
Duplicate of #978

**Closed** 2021-08-18 19:19 UTC
Labels: bug
