### ISSUE TITLE
popupLyrics.js doesn't show album cover 

### ISSUE THREAD

**Issue by KorayUlusan** [khanhas/spicetify-cli#1086] opened 2021-09-23 07:20 UTC
## ℹ Computer information

- Spotify version: 1.1.67 MacOS
- Spicetify version: 2.6.4, fresh install

### ❌ Problem

popupLyrics.js doesn't show album cover even if it is selected at its settings to do so.

**Comment by TheGeeKing** [comment] 2021-09-23 07:24
Duplicate of #1075

**Closed** 2021-09-23 07:24 UTC
Labels: bug
