### ISSUE TITLE
fatal error when applying?

### ISSUE THREAD

**Issue by collips** [khanhas/spicetify-cli#566] opened 2021-05-13 13:10 UTC
hello
i had no issues with spicetify since today. when i tried to apply my new color scheme, i got error "fatal open C:\Users\h\AppData\Roaming\Spotify\Apps\zlink\css\user.css: No such file of directory.". i couldnt find any better option than uninstall both spicetify and spotify and reinstall it again. it worked but after i close spotify, my theme was gone again and when i try to apply on powershell it gave me the same error. is this because spotify got updates? any solutions?

**Comment by SaruDesu** [comment] 2021-05-13 13:13
Duplicate of #564

**Closed** 2021-05-14 11:26 UTC
