### ISSUE TITLE
Spicetify not working after enabling lyrics-plus

### ISSUE THREAD

**Issue by Hagenbeck** [khanhas/spicetify-cli#1213] opened 2021-11-01 20:47 UTC
## ℹ Computer information
- running latest Version of Windows 10
- Spicetify version: 2.7.1

after enabling lyrics plus with "spicetify config custom_apps lyrics-plus" the window stays empty and I get following error message in the dev-tools:
empty window:
![image](https://user-images.githubusercontent.com/78031118/139739916-3eff1a2b-be6d-4e49-96f6-a6efe1e972e9.png)

error message:
![image](https://user-images.githubusercontent.com/78031118/139739683-09be05d2-b7a3-472a-b4d2-e50733905698.png)
I already reinstalled spicetify and lyrics-plus but nothing changed.
When I disable lyrics-plus again spicetify starts as usually

**Comment by TheGeeKing** [comment] 2021-11-01 21:35
Duplicate of #1204

**Comment by grastraa** [comment] 2021-11-02 16:17
> 
> 
> Duplicate of #1204

It might be useful for that issue to not be marked as resolved until the release solving them is up. 
If an individual comes here to post an issue, they are more likely to see that thread, and threads like these may be 10% less common.

**Comment by TheGeeKing** [comment] 2021-11-02 16:39
> > 
> > 
> > Duplicate of #1204
> 
> It might be useful for that issue to not be marked as resolved until the release solving them is up. 
> If an individual comes here to post an issue, they are more likely to see that thread, and threads like these may be 10% less common.

Basic thing when you have an issue is to find something similar, so open or close issues (a closed one will have more chance to have an answer).

If people don't want or don't do that, I think they don't want to find an answer to their question. So their problem.

For us, maintainers and contributors, it makes it more readable and maintainable to have only actual issues and not already fixed one that people just need to wait for the release.

So please @Hagenbeck close this issue.

**Closed** 2021-11-02 17:22 UTC
Labels: bug, custom app
