### ISSUE TITLE
[Help] No Render On spotify After Running sudo -E spicetify backup apply enable-devtool

### ISSUE THREAD

**Issue by AiryPP** [khanhas/spicetify-cli#964] opened 2021-08-15 04:47 UTC
Hey there I was just trying to use a spicetify theme for my new Arch rice and ran into a problem after running the command sudo -E spicetify backup apply enable-devtool, nothing will render regardless of the theme.

Any help is appreciated

**Comment by Shayshon** [comment] 2021-08-15 05:21
Can Reproduce- Windows 11 build 22000.132 on newest Spotify build

**Comment by itsmeow** [comment] 2021-08-15 13:56
Duplicate of #845, patch available (see #945)

**Comment by AiryPP** [comment] 2021-08-16 15:02
Patch not working for me

Spotify Run Logs
```
(spotify:37153): Gtk-WARNING **: 20:31:52.975: Theme parsing error: gtk-dark.css:6342:10: 'height' is not a valid property name
Gtk-Message: 20:31:52.994: Failed to load module "appmenu-gtk-module"
/proc/self/exe: /usr/lib/libcurl-gnutls.so.4: no version information available (required by /proc/self/exe)
```

**Comment by itsmeow** [comment] 2021-08-17 01:48
@AiryPP Can you tell me your OS and CPU architecture?

**Comment by AiryPP** [comment] 2021-08-18 04:25
@itsmeow ArchLinux cpu Architecture is x86 64 bit

**Closed** 2021-08-31 12:30 UTC
Labels: bug
