### ISSUE TITLE
Error message shuffle play

### ISSUE THREAD

**Issue by biggybean** [khanhas/spicetify-cli#1073] opened 2021-09-19 13:38 UTC
## ℹ Computer information

- Spotify version: Spotify for Windows 1.1.68.628.geb44bd66
- Spicetify version: 2.6.4

## 📝 Provide detailed reproduction steps (if any)

1. Choose any playlist
2. Choose context menu entry "Play with Shuffle+"

### ✔️ Expected result

Shuffled playlist starts playing

### ❌ Actual result
Error message, see screenshot

## 📷 Screenshots
![grafik](https://user-images.githubusercontent.com/22399149/133929580-b0a21ce3-6551-44e8-88e9-b56d08ddd45a.png)

EDIT: Just noticed that the message pops up with spotifiy's own shuffle play as well, so it's not a shuffle+ issue.

**Comment by afonsojramos** [comment] 2021-09-20 13:02
Thank you @biggybean, we'll investigate this issue.

**Comment by daksh2k** [comment] 2021-09-20 15:14
> EDIT: Just noticed that the message pops up with spotifiy's own shuffle play as well, so it's not a shuffle+ issue.

I also face this issue sometimes, I think this happens because when auto shuffle is on and  Spicetify takes over that play/shuffle button resulting in the same error. 
To get around this I usually directly play a track from a playlist and not the play/shuffle button on top.

I have only noticed this issue when the desktop app is open for quite some time and music has not been played for 1-2 hours, then this error comes up maybe it's a token refresh issue on auto shuffle in shuffle+ but I am not sure!

**Comment by afonsojramos** [comment] 2021-09-29 23:28
So far I haven't been able to reproduce this issue, @biggybean @daksh2k does it keep happening?

@daksh2k if you are correct, we might as well close this issue since it is related to Spotify and not Spicetify

**Comment by biggybean** [comment] 2021-09-30 06:44
@afonsojramos With the newest versions of both spotify and spicetify, it works! Should I close it or is that up to you?

**Comment by afonsojramos** [comment] 2021-09-30 07:27
You'd have closed it, but it's the same in the end. Thanks!

**Closed by afonsojramos** 2021-09-30 07:27 UTC
Labels: bug
