### ISSUE TITLE
Error applying themes

### ISSUE THREAD

**Issue by tommywxd** [khanhas/spicetify-cli#867] opened 2021-07-10 15:15 UTC
## ℹ Computer information

- Spotify version: 1.1.63.568.gda8cb5ac-a
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. Run `spicetify apply`

### ✔️ Expected result

It applys the themes + plugins

### ❌ Actual result

It errors

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/62763456/125167742-e7322080-e199-11eb-8269-2fb2e0477b53.png)

**Comment by Theblockbuster1** [comment] 2021-07-10 16:39
Duplicate of #845.

**Closed** 2021-07-10 17:03 UTC
Labels: bug
