### ISSUE TITLE
Something went wrong always appearing

### ISSUE THREAD

**Issue by Pkapakapa** [khanhas/spicetify-cli#1116] opened 2021-09-30 11:42 UTC
## ℹ Computer information

- Spotify version: 1.1.69.612.gb7409acb
- Spicetify version: 2.6.6

## 📝 Provide detailed reproduction steps (if any)
![Untitled](https://user-images.githubusercontent.com/91627695/135448969-5c83a75b-578e-4f65-a47f-e24465891017.png)

1. …
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_

### ❌ Actual result

_What is the actual result of the above steps?_

## 📷 Screenshots

_Are there any useful screenshots?_

**Comment by TheGeeKing** [comment] 2021-09-30 12:34
Please provide the needed info: Spotify and spicetify version

**Comment by Pkapakapa** [comment] 2021-09-30 12:44
spicetify v 2.6.6
spotify latest version (just updated)
even with the prior version of spotify it would give the same result

**Comment by TheGeeKing** [comment] 2021-09-30 12:50
> spicetify v 2.6.6
> 
> spotify latest version (just updated)
> 
> even with the prior version of spotify it would give the same result

Edit your original post and give the Spotify version (on windows: top left corner "Help" ==> "About Spotify")

**Comment by Pkapakapa** [comment] 2021-09-30 19:05
Apologies for that. It is still not working tho

**Comment by afonsojramos** [comment] 2021-09-30 22:28
Duplicate of #1112

**Closed by afonsojramos** 2021-09-30 22:28 UTC
Labels: bug
