### ISSUE TITLE
Lyrics tab not working

### ISSUE THREAD

**Issue by Mystik01** [khanhas/spicetify-cli#1263] opened 2021-11-12 18:28 UTC
## ℹ Computer information

- Spotify version: Spotify for Windows 1.1.72.439.gc253025e
- Spicetify version: 2.8.0

## 📝 Provide detailed reproduction steps (if any)

1. Updated to Spicetify 2.8.0
2. Opened lyrics tab, doesn't work.

### ❌ Actual result

Error page, 
```vendor~xpui.js:29 ChunkLoadError: Loading chunk spicetify-routes-lyrics-plus failed.
(missing: https://xpui.app.spotify.com/spicetify-routes-lyrics-plus.js)
    at Object.s.f.j (xpui.js:1)
    at xpui.js:1
    at Array.reduce (<anonymous>)
    at Function.s.e (xpui.js:1)
    at xpui.js:1
    at vendor~xpui.js:29
    at xs (vendor~xpui.js:29)
    at Ts (vendor~xpui.js:29)
    at Os (vendor~xpui.js:29)
    at gs (vendor~xpui.js:29)
```

## 📷 Screenshots

_Are there any useful screenshots?_
![image](https://user-images.githubusercontent.com/65687597/141516526-88b82761-e64a-4b41-874f-659c373ba7c7.png)

**Comment by TheGeeKing** [comment] 2021-11-12 18:30
Duplicate of #1252

**Comment by TheGeeKing** [comment] 2021-11-12 18:32
@itsmeow

**Closed** 2021-11-12 18:53 UTC
Labels: bug, custom app

**Comment by khanhas** [comment] 2021-11-13 01:49
Upgrade spicetify v2.8.1 and it should work now
