### ISSUE TITLE
Cannot find symbol for Custom app React symbols

### ISSUE THREAD

**Issue by hsspratt** [khanhas/spicetify-cli#876] opened 2021-07-12 12:16 UTC
## ℹ Computer information

- Spotify version: 1.1.63.568.gda8cb5ac-a
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

When Spotify updated when I tried to backup spicetify Spotify would go compeletely white when opened therefore I uninstalled then reinstalled.

1. curl -fsSL https://raw.githubusercontent.com/khanhas/spicetify-cli/master/install.sh | sh
2. export PATH=$PATH:/Users/harry/spicetify-cli/spicetify 
3. spicetify
4. spicetify -c
5. spicetify apply

### ✔️ Expected result

_What is the expected result of the above steps?_

That Spotify opens with the spicetify default theme

### ❌ Actual result

_What is the actual result of the above steps?_

Spotify opens to a blank white screen

## 📷 Screenshots

_Are there any useful screenshots?_

<img width="1440" alt="Screenshot 2021-07-12 at 13 15 21" src="https://user-images.githubusercontent.com/42693405/125286090-4b2c2480-e313-11eb-8a0c-7309cd1c7c33.png">
<img width="1440" alt="Screenshot 2021-07-12 at 13 15 08" src="https://user-images.githubusercontent.com/42693405/125286096-4cf5e800-e313-11eb-8b9c-1c848a9e1509.png">
<img width="382" alt="Screenshot 2021-07-12 at 13 14 59" src="https://user-images.githubusercontent.com/42693405/125286097-4cf5e800-e313-11eb-8eb8-7ee637cac18a.png">
<img width="412" alt="Screenshot 2021-07-12 at 13 14 38" src="https://user-images.githubusercontent.com/42693405/125286100-4d8e7e80-e313-11eb-9dd6-1fb2ab7c9c86.png">

**Comment by starbvuks** [comment] 2021-07-12 12:19
i'm having this exact same issue

**Comment by afonsojramos** [comment] 2021-07-12 12:21
Duplicate of #845

**Closed by afonsojramos** 2021-07-12 12:21 UTC
Labels: bug
