### ISSUE TITLE
spotify updating to a new version when changing/editing themes

### ISSUE THREAD

**Issue by Nerxxy** [khanhas/spicetify-cli#869] opened 2021-07-10 20:06 UTC
## ℹ Computer information

- Spotify version: 1.1.63.568.gda8cb5ac
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. Not too sure but it happened under one of these conditions - change/edit themes quite a few times
2. …
3. …

### ✔️ Expected result

Themes to change and not spotify updating

### ❌ Actual result

After a certain amount of applying themes/time (not sure which) spotify just decides to update after doing "spicetify apply" in powershell or restarting spotify.

## Extra Info 

In the config-xpui.ini it shows that spotify version is 1.1.62.583.gdac868ed but once spotify "updates" it changes to 1.1.63.568.gda8cb5ac, and when its "updated" and I do "spicetify apply" in powershell I get an error stating "Cannot find symbol for Custom app React symbols"

After all of this, if I uninstall spotify and then go to the spotify website and download a fresh spotify installer and reinstall spotify which it reinstalls to the version of spotify that actually works with spicetify, so I go back to powershell and do the necessary things to get it back up and running, it works fine for a period of time/theme changes before spotify "updates" again therefore breaking spicetify again

## 📷 Screenshots

Shows error message in powershell
![image](https://user-images.githubusercontent.com/37718547/125174973-08f2ce00-e1c1-11eb-81d8-a60e06c49061.png)

This is the config-xpui.ini before and after spotify updating, Left is before the update (when spicetify was working)
![image](https://user-images.githubusercontent.com/37718547/125175147-f927b980-e1c1-11eb-8687-4a87b23e1081.png)

**Comment by Nerxxy** [comment] 2021-07-10 21:04
Idk whats happened but things seem to be fine now? will report back again when/if it breaks again

**Comment by bilgehnbilge** [comment] 2021-07-10 21:43
Same issue for me. How can I fix this? I delete all custom apps but it's same error. "Cannot find symbol for Custom app React symbols"

**Comment by Nerxxy** [comment] 2021-07-10 23:00
> Same issue for me. How can I fix this? I delete all custom apps but it's same error. "Cannot find symbol for Custom app React symbols"

im not too sure there is a fix, that we can do, since im looking at spotify right now and its saying that there is an update, so it may be the spotify update thats broken thing? so all i can say is to just not update spotify. i havent updated yet to test but im 99% sure that if i do update it'll break

**Comment by Akasiek** [comment] 2021-07-10 23:38
Same here. Even deleting custom apps doesn't fix it. Spotify is opening but it's all one color only (background color) and it's making my CPU hurt...

**Comment by VolkanKorki** [comment] 2021-07-11 09:09
I am getting the exact same error as well, it didn't seem to fix itself for me.
![image](https://user-images.githubusercontent.com/53551160/125189426-b1944280-e240-11eb-95de-ac6cd2f3b326.png)

**Comment by Daksh777** [comment] 2021-07-11 14:10
Duplicate of #845

**Closed** 2021-07-11 14:31 UTC
Labels: bug
