### ISSUE TITLE
Spotify Reacts with a blank screen after installing spicetify.

### ISSUE THREAD

**Issue by theofficialgrand1** [khanhas/spicetify-cli#947] opened 2021-08-04 04:18 UTC
## ℹ Computer information
macOS Big Sur
- Spotify version: 
1.1.64.561.g71bd09eb-a
- Spicetify version: 
Latest?

## 📝 Provide detailed reproduction steps (if any)

When running the command "spicetify backup apply enable-devtool"

###Result

```
spicetify v
Backing up app files:
OK
Extracting:
OK
Preprocessing:
OK
OK
success Everything is ready, you can start applying now!
Copying raw assets:
OK
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
OK
success Spotify is spiced up!
```
## 📷 Screenshots

<img width="563" alt="Screen Shot 2021-08-04 at 12 16 53 PM" src="https://user-images.githubusercontent.com/78011648/128121366-30dedeee-6ada-4d12-8038-0bf97e15f076.png">
<img width="1394" alt="Screen Shot 2021-08-04 at 12 18 36 PM" src="https://user-images.githubusercontent.com/78011648/128121500-a5158be8-df63-4b95-9144-ed3594cfbdfb.png">

**Comment by saxobroko** [comment] 2021-08-04 06:05
Duplicate of #845

**Comment by theofficialgrand1** [comment] 2021-08-05 02:07
> Duplicate of #845
> 
> There is a community patch available.

There isn't a Mac solution.

**Comment by Woosy** [comment] 2021-08-05 11:23
> > Duplicate of #845
> > There is a community patch available.
> 
> There isn't a Mac solution.

The patch also works for MacOS, I'm currently using it on BigSur

**Comment by WolfgangDS** [comment] 2021-08-05 20:17
> 
> 
> Duplicate of #845
> 
> There is a community patch available.

Where can I find this community patch?  I'm really unfamiliar with how github works.

**Comment by itsmeow** [comment] 2021-08-06 00:07
#945 or the comments of #845
Link to latest patch: https://github.com/itsmeowForks/spicetify-cli/releases/tag/v2.5.0-patch2

**Comment by WolfgangDS** [comment] 2021-08-06 02:32
> 
> 
> #945 or the comments of #845
> Link to latest patch: https://github.com/itsmeowForks/spicetify-cli/releases/tag/v2.5.0-patch2

Thanks a million!  Took some doing to get it to work with Rainmeter (mostly just me being dumb), but it works perfectly now.

**Comment by theofficialgrand1** [comment] 2021-08-06 07:07
> > > Duplicate of #845
> > > There is a community patch available.
> > 
> > 
> > There isn't a Mac solution.
> 
> The patch also works for MacOS, I'm currently using it on BigSur

How do you install it?

**Comment by theofficialgrand1** [comment] 2021-08-06 07:19
How do you install that patch? The instructions are useless.

**Comment by casungo** [comment] 2021-08-06 10:45
> How do you install that patch? The instructions are useless.

Download the .exe and replace it with the one in C:\Users\YourUserName\spicetify-cli\
and it should be done

**Closed** 2021-08-10 17:42 UTC
Labels: bug

**Comment by afonsojramos** [comment] 2021-08-10 19:31
The fix will be released soon!
