### ISSUE TITLE
Spotify is broken again!

### ISSUE THREAD

**Issue by martinotecco** [khanhas/spicetify-cli#1205] opened 2021-10-29 17:18 UTC
## ℹ Computer information

- Spotify version: latest Windows version (1.1.71.560.gc21c3367)
- Spicetify version: latest Windows version (2.7.1)
- Custom apps used: [Lyrics Plus](https://github.com/khanhas/spicetify-cli/wiki/Custom-Apps#lyrics-plus) & [BlockTheSpot.bat](https://bit.ly/BlockTheSpot) (BlockTheSpot isn't a custom app, is a .bat file you run once after applying Spicetify patch to block any ads running in Spotify)
- OS: Windows 11
---

After latest Spotify Windows update (v1.1.71.560.gc21c3367) applying Spicetify patch causes the Spotify breakage. Please fix this issue quickly! Thanks!
1. spicetify upgrade
2. spicetify restore backup apply
=> Spotify breaks

⠀ spicetify apply
⠀ => Spotify breaks

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/57567466/139476164-931e6ae9-1480-492d-9869-edcdc6363112.png)

**Comment by applekillerbyjames** [comment] 2021-10-30 00:30
please reference issue #1204 , same issue

**Comment by itsmeow** [comment] 2021-10-30 12:59
Duplicate of #1204

**Closed** 2021-11-01 12:06 UTC
Labels: bug, custom app
