### ISSUE TITLE
Panic: Runtime Error

### ISSUE THREAD

**Issue by y0himba** [khanhas/spicetify-cli#859] opened 2021-07-09 13:04 UTC
## ℹ Computer information
OS Name	Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043
Other OS Description 	Not Available
OS Manufacturer	Microsoft Corporation
System Name	GHETTOPC
System Manufacturer	MSI
System Model	MS-7996
System Type	x64-based PC
System SKU	Default string
Processor	Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz, 3600 Mhz, 4 Core(s), 8 Logical Processor(s)
BIOS Version/Date	American Megatrends Inc. 2.G0, 5/15/2018
SMBIOS Version	3.0
Embedded Controller Version	255.255
BIOS Mode	UEFI
BaseBoard Manufacturer	MSI
BaseBoard Product	H110M PRO-D (MS-7996)

- Spotify version: 
1.1.63.568.gda8cb5ac-a

- Spicetify version: 
2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. …Spicetify backup
2. …Spicetify apply
3. …Error (Pasted below)

### ✔️ Expected result
Spice up Spotify after update and apply theme/extensions

_What is the expected result of the above steps?_
Backup an updated default Spotify
Apply theme and extensions after backup

### ❌ Actual result

_What is the actual result of the above steps?_
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc00082c000, 0x1aaa1f, 0x1aaa1f, 0xc00082c000)
        D:/Code/spicetify-cli/src/apply/apply.go:180 +0xda6
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc0000c6640, 0x3a, 0xc0001979d8)
        D:/Code/spicetify-cli/src/utils/utils.go:190 +0xdb
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc0000c6640, 0x3a, 0xc0001041c0, 0x3, 0x4, 0xc000104200, 0x3, 0x4, 0x101)
        D:/Code/spicetify-cli/src/apply/apply.go:155 +0x9e
github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc00000e480, 0x2d, 0xc0001041c0, 0x3, 0x4, 0xc000104200, 0x3, 0x4, 0x101)
        D:/Code/spicetify-cli/src/apply/apply.go:34 +0x484
github.com/khanhas/spicetify-cli/src/cmd.Apply(0xeb52d4, 0x5)
        D:/Code/spicetify-cli/src/cmd/apply.go:73 +0x598
main.main()
        D:/Code/spicetify-cli/spicetify.go:189 +0x519
![Clipboard01](https://user-images.githubusercontent.com/11462603/125082008-aa303600-e094-11eb-889a-253eed490a38.jpg)

## 📷 Screenshots

_Are there any useful screenshots?_

**Comment by st-den** [comment] 2021-07-09 13:11
Duplicate of #845

**Comment by y0himba** [comment] 2021-07-09 13:14
Thank you.

**Closed** 2021-07-09 13:28 UTC
Labels: bug
