### ISSUE TITLE
error Cannot find symbol for Custom app React symbols

### ISSUE THREAD

**Issue by Dr-DaNk** [khanhas/spicetify-cli#924] opened 2021-07-24 17:11 UTC
## ℹ Computer information

- Spotify version: Latest I guess?
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

apply spicetify, any theme.

### ✔️ Expected result

Spicetify works

### ❌ Actual result

Blank screen with background color. Dev console completely empty. no HTML, no sources, nothing.
error in title provided from powershell.

## 📷 Screenshots

https://imgur.com/a/O6OD2m6

**Comment by a1sop0s** [comment] 2021-07-24 18:25
Duplicate of #845

**Closed** 2021-08-01 13:50 UTC
Labels: bug
