### ISSUE TITLE
problem applying custom apps

### ISSUE THREAD

**Issue by DeadTec9s** [khanhas/spicetify-cli#1206] opened 2021-10-29 20:15 UTC
When having enabled custom apps such as new releases and lyricsplus from the spicetify file it leaves the app on a green screen
![image](https://user-images.githubusercontent.com/77972339/139495828-2069e6ae-5d75-4dfb-af52-5e5a83be5498.png) command ran

![image](https://user-images.githubusercontent.com/77972339/139495919-4aeb0eb7-5562-4013-b1c7-6cf16fe140d8.png)
result
the same thing happens with new-releases as well. Not sure if i messed up or something else

im using dribbblish dynamic and haven't really made any other changes
![image](https://user-images.githubusercontent.com/77972339/139496347-d46d6d4b-a14a-4189-8545-d32d83cdd0e7.png)
how it is normally

**Comment by emekoi** [comment] 2021-10-29 20:44
i can confirm i have the same issue, since the spotify client updated. checking the developer tools shows this error 
![image](https://user-images.githubusercontent.com/9454576/139499452-5923a059-81df-4af1-ba60-ad7e76f1400b.png)
leading me to believe there is something wrong with [this](https://github.com/khanhas/spicetify-cli/blob/6cd24c236bf9f676a91b929b45de255b1f1061dd/CustomApps/new-releases/Card.js#L65) line?

**Comment by Pomis** [comment] 2021-10-29 21:18
Same for me, subscribing for updates

**Comment by TheGeeKing** [comment] 2021-10-29 22:18
For the moment rollback and block updates.

For Windows:
```
del %localappdata%\Spotify\Update

mkdir %localappdata%\Spotify\Update

icacls %localappdata%\Spotify\Update /deny "%username%":D

icacls %localappdata%\Spotify\Update /deny "%username%":R
```

**Comment by applekillerbyjames** [comment] 2021-10-30 00:31
please reference issue #1204 , same issue

**Comment by itsmeow** [comment] 2021-10-30 12:59
Duplicate of #1204

**Comment by TheGeeKing** [comment] 2021-11-03 21:56
@DeadTec9s please close this issue.

**Comment by afonsojramos** [comment] 2021-11-04 12:57
Released new version! Please update before trying!

**Closed** 2021-11-04 12:57 UTC
Labels: custom app
