### ISSUE TITLE
Spicetify.expFeatureOverride is not a function

### ISSUE THREAD

**Issue by niwla23** [khanhas/spicetify-cli#1262] opened 2021-11-12 17:23 UTC
## ℹ Computer information

- Spotify version: 1:1.1.56.595-1 (AUR)
- Spicetify version: v2.8.0

## 📝 Provide detailed reproduction steps (if any)

1. Generate config and apply
2. see spotify greyscreen
3. right click > inspect element > console
4. you see the error

### ✔️ Expected result

it should work lol

### ❌ Actual result

Spicetify.expFeatureOverride is not a function

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/46248939/141508546-0aa0c300-0480-4f0d-a705-ee0a1b8fda83.png)

**Comment by ririxidev** [comment] 2021-11-12 17:49
AUR has version `1:1.1.72.439-1`, not `1:1.1.56.595-1`, 2.8.0 works only with >=1.1.72. Update your spotify version
@itsmeow to be closed.

**Comment by TheGeeKing** [comment] 2021-11-12 17:50
Duplicate of #1255

**Closed** 2021-11-12 17:50 UTC
Labels: bug

**Comment by khanhas** [comment] 2021-11-13 03:09
Upgrade your spotify to at least v1.1.69 and spicetify v2.8.1
