### ISSUE TITLE
blank when updating spotify

### ISSUE THREAD

**Issue by indrapalijama** [khanhas/spicetify-cli#1217] opened 2021-11-03 09:28 UTC
## ℹ Computer information

- Spotify version: Spotify for macOS (Intel) - 1.1.71.560.gc21c3367
- Spicetify version: 2.7.1

## 📝 Provide detailed reproduction steps (if any)

1. update spotify
2. spicetify suddenly not working
3. restore spicetify backup in CLI `spicetify backup apply`

### ✔️ Expected result

spotify and spicetify is working as usual

### ❌ Actual result

blank screen on spotify

## 📷 Screenshots

* apply spicetify backup, after updating spotify
![Screen Shot 2021-11-03 at 4 23 28 PM](https://user-images.githubusercontent.com/33986004/140036186-e769a2a7-700d-456e-8855-192fc01fe1c1.png)

* blank screen on spotify
![Screen Shot 2021-11-03 at 4 26 12 PM](https://user-images.githubusercontent.com/33986004/140036200-bf15e51a-023a-4d1c-8fed-5fc5f5f43792.png)

* error in developer console
<img width="862" alt="Screen Shot 2021-11-03 at 4 26 20 PM" src="https://user-images.githubusercontent.com/33986004/140036206-515cb1d1-75d0-4286-abdd-1233cff47181.png">

**Comment by casungo** [comment] 2021-11-03 18:11
#1208 fixes this but a new version needs to be released

**Comment by TheGeeKing** [comment] 2021-11-03 21:52
Duplicate of #1204. Please close this issue.

**Comment by indrapalijama** [comment] 2021-11-04 01:21
> #1208 fixes this but a new version needs to be released

i see, gotta waiting then

**Comment by indrapalijama** [comment] 2021-11-04 01:21
> Duplicate of #1204. Please close this issue. 

Okay

**Comment by TheGeeKing** [comment] 2021-11-04 09:23
> > Duplicate of #1204. Please close this issue. 
> 
> Okay

Please close this issue @indrapalijama

**Closed** 2021-11-04 09:24 UTC
Labels: bug, custom app
