### ISSUE TITLE
New Version Not Reported as Such

### ISSUE THREAD

**Issue by Fosmos** [khanhas/spicetify-cli#975] opened 2021-08-18 12:28 UTC
## ℹ Computer information

- Spotify version:  1.1.66.578.gc54d0f69-a
- Spicetify version: 2.6.0 (I presume)

## 📝 Provide detailed reproduction steps (if any)

1. Install Spicetify 2.6.0 (whether through the command line or by replacing the spicetify-cli directory with the 2.6.0 one)
2. try `spicetify --version`

### ✔️ Expected result
Displays 2.6.0

### ❌ Actual result
Displays 2.5.0-itsmeow-patch4

## 📷 Screenshots
![Screenshot 2021-08-18 082723](https://user-images.githubusercontent.com/59673626/129898028-26650937-5da1-4d93-8539-b617b605c8cb.png)

As an added bonus problem. Since the version being reported is incorrect, Spicetify always thinks it needs to upgrade. Alternatively the upgrade process is not working but I don't think that's the case since downloading the new version's zip and replacing the old files with it doesn't make a difference.

**Comment by casungo** [comment] 2021-08-18 23:30
Duplicate of #973

**Comment by edo2313** [comment] 2021-08-18 23:31
Duplicate of #973

**Comment by casungo** [comment] 2021-08-18 23:31
> Duplicate of #973

I arrived first hehe

**Comment by edo2313** [comment] 2021-08-18 23:41
@casungo Saw that, 17 seconds faster 😅

**Closed** 2021-08-31 12:40 UTC
Labels: bug
