### ISSUE TITLE
Trojan into spicetify.exe after a spicetify upgrade

### ISSUE THREAD

**Issue by LotharieSlayer** [khanhas/spicetify-cli#1244] opened 2021-11-08 22:05 UTC
uuh that's weird...
I just did a `spicetify upgrade` and then a `spicetify restore backup apply` into powershell and now that?
_EDIT : Btw I was in an admin powershell._

![image](https://user-images.githubusercontent.com/49253492/140825467-5b4ae99a-e3fa-4557-af1a-bb13d9eba158.png)

**Comment by jakublevy** [comment] 2021-11-08 22:27
Version 2.7.2 is only affected.
32-bit spicetify.exe 3/67 https://www.virustotal.com/gui/file/98229ef6f8683673273f49b61671ff6bbd4da72e00abc84f6696ab0761a29f63

64-bit spicetify.exe 20/68 https://www.virustotal.com/gui/file/9d421fe906870bc4a7e924ed9b068cdf0097806ecceeec3c7c312f330f673f44

**Comment by TheGeeKing** [comment] 2021-11-08 22:29
Duplicate of #1242

**Closed** 2021-11-08 22:30 UTC
Labels: bug, custom app
