### ISSUE TITLE
error Cannot find symbol for Custom app React symbols

### ISSUE THREAD

**Issue by DarkVillager** [khanhas/spicetify-cli#923] opened 2021-07-24 08:07 UTC
## ℹ Computer information

- Spotify version: 1.1.64.561.g71bd09eb-a
- Spicetify version: spicetify v2.4.0

## 📝 Provide detailed reproduction steps (if any)

1. Updated spotify to 1.1.64.561.g71bd09eb-a
2. Backup.
3. Apply theme like normal (all themes are broken)

### ✔️ Expected result

Spicetify theme should be applied

### ❌ Actual result

Blank screen with error Cannot find symbol for Custom app React symbols in cmd.

## 📷 Screenshots
[https://user-images.githubusercontent.com/42322979/126862078-7db9b925-47f5-4985-93af-556c9bae7e89.png](https://user-images.githubusercontent.com/42322979/126862078-7db9b925-47f5-4985-93af-556c9bae7e89.png)

**Comment by Tene21** [comment] 2021-07-24 08:51
Duplicate of #845

**Closed** 2021-07-24 09:42 UTC
Labels: bug
