### ISSUE TITLE
WebNowPlaying Broken on Latest Spotify

### ISSUE THREAD

**Issue by Fosmos** [khanhas/spicetify-cli#1415] opened 2022-01-19 16:47 UTC
## ℹ Computer information

- Spotify version:  1.1.77.643.g3c4c6fc6
- Spicetify version: 2.8.4

Nothing appears to be working (no cover, media controls, or info). Additionally, Rainmeter shows no errors or warnings in the log.

Tested on two seperate skins that use the plugin:
https://visualskins.com/skin/cleartext
https://www.deviantart.com/fosmos/art/Simply-858119562

**Comment by ToasterDEV** [comment] 2022-01-19 18:23
Can confirm this issue as well, the console reports the following:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'getVolume')
    at Object.getVolume (spicetifyWrapper.js:36)
    at updateInfo (webnowplaying.js:58)
getVolume@spicetifyWrapper.js:36
updateInfo@webnowplaying.js:58
```

**Comment by DanBeast1337** [comment] 2022-01-19 18:56
You can (temporarily, until it's fixed) make it work again, by commenting out **Line 58** in **webnowplaying.js**

`        //storage.VOLUME = Math.round(Spicetify.Player.getVolume() * 100);`
then just `spicetify apply`

Depending on what you use with Rainmeter, there may be issues with Volume control or fetching the current volume, but everything else works.

**Comment by NikolasKomonen** [comment] 2022-01-21 17:19
Just want to add in, since I was initially modifying the wrong `webnowplaying.js` file.
Run this to get the path of the file:
`spicetify -e path webnowplaying.js`

**Comment by daplon** [comment] 2022-01-22 14:28
My Webnowplaying.js stops working after 5 mins, progress and position info stops getting info. 
Anyone more with that problem?

**Comment by machinemessiah** [comment] 2022-01-23 05:13
The volume methods and events have moved from Player.origin to Platform.PlaybackAPI; I've attempted a fix for this change ([see here](https://github.com/khanhas/spicetify-cli/pull/1424)), but at the moment it still requires extensions which listen for volume events to attach their listeners to Platform.PlaybackAPI._events (assuming my fix works and gets merged).

**Comment by DanBeast1337** [comment] 2022-01-23 11:16
> I've attempted a fix for this change (see here: #1424 )

Replacing the lines you changed makes it work again, _without_ commenting out anything in webnowplaying.js, so that's something.

**Comment by charmarkk** [comment] 2022-01-29 03:55
> You can (temporarily, until it's fixed) make it work again, by commenting out **Line 58** in **webnowplaying.js**
> 
> ` //storage.VOLUME = Math.round(Spicetify.Player.getVolume() * 100);` then just `spicetify apply`
> 
> Depending on what you use with Rainmeter, there may be issues with Volume control or fetching the current volume, but everything else works.

This didn't work for me, unless I somehow edited the wrong file. No change.

**Comment by borsTiHD** [comment] 2022-01-29 09:04
Working for me by commenting out Line 58 in webnowplaying.js.
I just needed to run `spicetify apply` again.

**Comment by charmarkk** [comment] 2022-01-29 21:40
> ~~This didn't work for me, unless I somehow edited the wrong file. No change.~~

I reinstalled via chocolately and it's working for me now. Maybe I had the wrong file/an old installation issue. Great fix @DanBeast1337!

**Comment by afonsojramos** [comment] 2022-02-01 00:22
#1424 seems to have fixed this.

**Closed by afonsojramos** 2022-02-01 00:22 UTC
Labels: bug

**Comment by Sol1vaN** [comment] 2023-09-01 14:59
the problem is back, i've commented the line

`storage.VOLUME = Math.round(Spicetify.Player.getVolume() * 100);`

but nothing happens, the actual versions are:

- Spotify Windows (64 bits) 1.2.19.941.gbf202593
- Spicetify v2.23.0

the script that i'm executing are:
```
iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-cli/master/install.ps1 | iex
iwr -useb https://raw.githubusercontent.com/spicetify/spicetify-marketplace/main/resources/install.ps1 | iex
```

anybody has the same problem now?

**Comment by daplon** [comment] 2023-09-01 15:03
I need to reinstall spotify, claear backups and aply again the inyect of webnowplaying. And is working again.
