### ISSUE TITLE
Spotify breaking because of Spicetify

### ISSUE THREAD

**Issue by tobilouv2** [khanhas/spicetify-cli#927] opened 2021-07-25 16:32 UTC
## ℹ Computer information

- Spotify version: 1.1.64.561
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. … I am using the Dribbilish theme customized to my liking and when it opens it shows a error kinda code and wont let me exit it
2. … I have been trying for 1 day to fix this by updating the theme js plugin, updating the theme folder, and uninstalling spotify and other.
3. … 

### ✔️ Expected result

Spotify to work and play songs.

 
### ❌ Actual result

 error message on open : error-dialog.generic.header and under error-dialog.generic.body and fatal-error.button.label

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/76414744/126906382-8af7b21b-1088-4b85-9d57-830eec53ee90.png)

**Comment by rojnwa** [comment] 2021-07-26 11:38
Have the same issues after updating to current version (1.1.64.561.g71bd09eb).

Downgrading to 1.1.63.568.gda8cb5ac fixes the problem for now.

**Comment by tobilouv2** [comment] 2021-07-26 23:19
> Have the same issues after updating to current version (1.1.64.561.g71bd09eb).
> 
> Downgrading to 1.1.63.568.gda8cb5ac fixes the problem for now.

Ok.

**Comment by Eden333** [comment] 2021-07-29 10:16
> Have the same issues after updating to current version (1.1.64.561.g71bd09eb).
> 
> Downgrading to 1.1.63.568.gda8cb5ac fixes the problem for now.

how would I do that?

**Comment by ShivaPrakash-006** [comment] 2021-07-30 05:40
Search the internet, it is there.

**Comment by ShivaPrakash-006** [comment] 2021-07-30 05:42
https://filehippo.com/download_spotify/

**Comment by itsmeow** [comment] 2021-08-06 00:08
Duplicate of #845 
Patch available: #945 https://github.com/itsmeowForks/spicetify-cli/releases/tag/v2.5.0-patch2

**Comment by Eden333** [comment] 2021-08-10 01:44
> Duplicate of #845
> Patch available: #945 https://github.com/itsmeowForks/spicetify-cli/releases/tag/v2.5.0-patch2

I did apply the patch but.. is there a way to also get rainmeter working with it again?

![image](https://user-images.githubusercontent.com/18154402/128795719-79244d92-3964-44f7-8838-c6c1d4864dc9.png)

**Comment by itsmeow** [comment] 2021-08-11 03:24
@Eden333 I've not had any issues with Rainmeter or webnowplaying.js. Maybe check the developer console for errors? Also make sure webnowplaying is still in your extensions.

**Comment by Eden333** [comment] 2021-08-13 10:17
> @Eden333 I've not had any issues with Rainmeter or webnowplaying.js. Maybe check the developer console for errors? Also make sure webnowplaying is still in your extensions.

which dev console? Powershell isnt giving me any errors

**Comment by Daggy1234** [comment] 2021-08-16 20:07
I'm also getting the same error, I've tried restoring, updating the back etc.

**Comment by itsmeow** [comment] 2021-08-17 01:46
@Daggy1234 This is a duplicate issue, there is a fix available here #945

**Comment by afonsojramos** [comment] 2021-08-17 17:39
Please update to v2.6.0 and retry, thanks!

**Closed by afonsojramos** 2021-08-17 17:39 UTC
Labels: bug

**Comment by yuceltoluyag** [comment] 2022-08-21 10:32
@afonsojramos  
```
spicetify --version
2.11.1
Spotify version 1.1.84.716.gc5f8b819
```
sorry to write again on this question I looked in your documentation and didn't see any note that a specific spotify is running. Does it only work on a specific Spotify version?

I am also facing the same error
> x Actual result
> error message on open : error-dialog.generic.header and under error-dialog.generic.body and fatal-error.button.label
