### ISSUE TITLE
Cannot download version 2.6

### ISSUE THREAD

**Issue by OhItsTom** [khanhas/spicetify-cli#1017] opened 2021-08-31 20:17 UTC
## ℹ Computer information

- Spotify version: All
- Spicetify version: N/A

## 📝 Provide detailed reproduction steps (if any)

1. Install any version of spotify
2. Try to install v2.6 using ```$v='2.6.0'; Invoke-WebRequest -UseBasicParsing 'https://raw.githubusercontent.com/OhItsTom/spicetify-easyinstall/Spicetify-v2/install.ps1' | Invoke-Expression```
3. Realise that you are still on version 2.5.0-itsmeow-patch4

### ✔️ Expected result

v2.6 is installed.

### ❌ Actual result

2.5 is installed.

### Feel free to try and reproduce the problem using this: https://github.com/OhItsTom/spicetify-easyinstall.
Noticed the problem whilst updating the spahgetti code, not sure of a work around. Upgrade also doesnt work.

**Comment by TheGeeKing** [comment] 2021-08-31 20:23
Duplicate of #973

**Comment by TheGeeKing** [comment] 2021-08-31 20:28
I let you read it again.
https://github.com/khanhas/spicetify-cli/issues/973#issuecomment-900686400
> Yeah, sorry, tried to rush the release, will be fixed on the next one!
It is just a graphical text not updated during the release
The version that you have is 2.6 it just displays `2.5.0-itsmeow-patch4`

I hope I have helped!
If you need more assistance with Spotify or Spicetify, I will always be here for you. Ping me and your personal helper will appear :)
If you are not on the Spicetify discord -> https://discord.gg/VnevqPp2Rr and ping TheGeeKing#7841

**Closed** 2021-08-31 21:58 UTC
Labels: bug
