### ISSUE TITLE
Error after following Fluent installation instructions persists even after reinstalling spotify and spicetify

### ISSUE THREAD

**Issue by ianrispin** [khanhas/spicetify-cli#1356] opened 2021-12-10 06:51 UTC
## ℹ Computer information

- Spotify version: 1.1.73.517.gbef50fdb
- Spicetify version: v2.8.3
- MacBook Pro 13-inch, 2019 running macOS Big Sur

## 📝 Provide detailed reproduction steps (if any)

After following the installation instructions for the Fluent theme, I got this message upon opening spotify:
![Spotify error message](https://user-images.githubusercontent.com/50210259/145482094-572320c8-7c2c-468f-9bde-ffd8d66cbaa2.png)
I opened the devtools and had a few error messages in the console (don't have a screenshot of these). I suspected the culprit to be [this](https://github.com/morpheusthewhite/spicetify-themes/tree/master/Fluent#important) step in the fluent instructions. 
Decided to uninstall and reinstall spotify and spicetify. I didn't do anything with the themes this time, and it seemed to be working until I installed the newReleases extension and spotify gave me the same error message. Below is a screenshot of the current error messages in the devtools:
![devtools error messages](https://user-images.githubusercontent.com/50210259/145529527-5a2a86fd-22a6-4180-8e99-8c3597c98e4d.png)
If I run 'spicetify restore' then spotify works again, but I don't know how else to fix it.

### ✔️ Expected result

Errors should be gone after reinstalling spicetify and spotify

### ❌ Actual result

Errors still persist

**Comment by Ddangkri** [comment] 2021-12-10 07:44
#1257 Maybe similar with this? Btw I have the same issue.

**Comment by Ddangkri** [comment] 2021-12-10 07:58
Umm.. I downgraded Spotify to 1.1.73.517.gbef50fdb (the same mentioned in the issue) while I didn't touch anything on Spicetify, and it works. Maybe removing newReleases Extension can be the solution. Sometimes those extensions are not compatible with new version of Spotify.

**Comment by rcompier** [comment] 2021-12-10 07:59
From my own testing, I found out that the error lies within `lyrics-plus` from the custom apps.

After removing it from the config everything runs fine again.

**Comment by Ddangkri** [comment] 2021-12-10 08:15
Actually my spicetify runs fine with `lyrics-plus` custom app, but removing custom apps or extensions one by one can be the best solution.

**Comment by mrtolkien** [comment] 2021-12-10 14:10
Same here, have been issues with `lyrics-plus` after the last Spotify update

**Comment by SupLiCatinG** [comment] 2021-12-10 16:46
> Same here, have been issues with `lyrics-plus` after the last Spotify update

did you try new lyrics-plus with 1.1.74 ?

**Comment by ianrispin** [comment] 2021-12-10 22:41
I'm running the latest version of lyrics plus (I installed spicetify 2 days ago and started having problems yesterday). I discovered that if I remove the lyrics-plus and new-releases custom apps then spotify works but spicetify doesn't (I also have bookmarks.js installed but it's not showing up now). Honestly, the new-releases app was the feature I was most excited about when I saw it, so for now, I'll be happy if I can just get that working again.

**Comment by TheGeeKing** [comment] 2021-12-11 09:12
Hi @ianrispin,

Can you make sure that your spicetify and  spotify version are 2.8.3 and 1.1.73.
You should have no issue for those versions, but Spotify just started to roll out a new update 1.1.74 that breaks custom apps.
If you have Spotify 1.1.74 i recommend you to rollback to 1.1.73 (you can find link online to old installer) and block updates:
1. In the Application folder, right-click on the Spotify app and choose 'Get Info'
2. in the 'Get info' window, make sure you check 'Locked', right at the top.

**Comment by ianrispin** [comment] 2021-12-11 10:40
> Hi @ianrispin,
> 
> Can you make sure that your spicetify and spotify version are 2.8.3 and 1.1.73. You should have no issue for those versions, but Spotify just started to roll out a new update 1.1.74 that breaks custom apps. If you have Spotify 1.1.74 i recommend you to rollback to 1.1.73 (you can find link online to old installer) and block updates:
> 
> 1. In the Application folder, right-click on the Spotify app and choose 'Get Info'
> 2. in the 'Get info' window, make sure you check 'Locked', right at the top.

Should I uninstall my current version before installing 1.1.73?

**Comment by TheGeeKing** [comment] 2021-12-11 18:15
Hi @ianrispin,

No need to, Spotify overwrite when you install it. Please close this issue as it is a duplicate of #1344.

**Closed** 2021-12-11 20:27 UTC
Labels: bug, custom app, extension

**Comment by ianrispin** [comment] 2021-12-11 20:50
I tried downloading an older version from filehippo and uptodown but each time, it downloaded as the latest version of spotify. Can somebody help?

**Comment by SupLiCatinG** [comment] 2021-12-11 21:52
> I tried downloading an older version from filehippo and uptodown but each time, it downloaded as the latest version of spotify. Can somebody help?

Are you a mac user or windows ? for mac 1.1.73 and 1.1.72 not available for download the file size need to be more than 100mb otherwise it will download latest version.

**Comment by ianrispin** [comment] 2021-12-11 22:03
Well, darn. Yeah I'm on mac, guess I'll wait for the next spicetify update. Should I reopen the issue?

**Comment by SupLiCatinG** [comment] 2021-12-11 22:05
no need, try this version until next update
![image](https://user-images.githubusercontent.com/94017480/145693014-26e810eb-4139-41bb-b64c-14c857d9ab5a.png)

**Comment by ianrispin** [comment] 2021-12-11 22:06
What site did you download that from?

**Comment by SupLiCatinG** [comment] 2021-12-11 22:07
uptodown

**Comment by ianrispin** [comment] 2021-12-11 22:17
Thanks, that worked!

**Comment by SupLiCatinG** [comment] 2021-12-11 22:18
If you are having issues with homepage try disabling "home config" in config

**Comment by ianrispin** [comment] 2021-12-11 22:50
Should I open a new issue on how custom apps aren't working on the latest spotify version?

**Comment by TheGeeKing** [comment] 2021-12-12 16:04
> Should I open a new issue on how custom apps aren't working on the latest spotify version?

Nop #1344 is already there
