### ISSUE TITLE
After applying a theme or extension, spotify just becomes a solid color

### ISSUE THREAD

**Issue by Ast3r0ids** [khanhas/spicetify-cli#887] opened 2021-07-13 08:06 UTC
## ℹ Computer information
-OS: Windows 10
- Spotify version: Latest
- Spicetify version: Latest

## 📝 Provide detailed reproduction steps (if any)

1. I install the theme
2. I install any extensions
3. I use "spicetify apply"
4. I get a few errors from symbol junk
5. I get a success message from spicetify saying spotify is patched
### ✔️ Expected result
The theme and extensions have been applied successfully

### ❌ Actual result
Spotify just becomes a solid colour with no buttons visible apart from window controls

## 📷 Screenshots
![Screenshot 2021-07-13 090335](https://user-images.githubusercontent.com/85231847/125415013-5aa6bc4b-8507-4ad8-b017-58316db84112.png)
 What spotify looks like after

![image](https://user-images.githubusercontent.com/85231847/125415098-a5043c6e-1d82-41be-8698-479478a522cb.png)
The terminal after installing the theme and extensions

Many thanks.

**Comment by Nice3point** [comment] 2021-07-13 08:35
A similar problem, everything stopped working today
![изображение](https://user-images.githubusercontent.com/20504884/125419371-9ca85592-df30-445f-9703-a7ec24db08da.png)

**Comment by afonsojramos** [comment] 2021-07-13 09:01
Duplicate of #845. However, @Ast3r0ids, you also have an non-existent extension on your config.

**Closed by afonsojramos** 2021-07-13 09:01 UTC
Labels: bug
