### ISSUE TITLE
error Cannot find symbol for Custom app React symbols after Spotify update

### ISSUE THREAD

**Issue by AntalaFilip** [khanhas/spicetify-cli#865] opened 2021-07-10 07:22 UTC
## ℹ Computer information

- Spotify version: 1.1.63.568.gda8cb5ac-a
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. Update Spotify to version above, Spotify resets to default theme
2. Run `spicetify apply` to apply theme, which asks me to run step 3, answer no and run step 3
3. Run `spicetify backup apply`

### ✔️ Expected result

Apply backup and let me run `spicetify apply`

### ❌ Actual result
```
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc00082c000, 0x1aaa1f, 0x1aaa1f, 0xc00082c000)
        D:/Code/spicetify-cli/src/apply/apply.go:180 +0xda6
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc0000ad000, 0x38, 0xc0003e59d8)
        D:/Code/spicetify-cli/src/utils/utils.go:190 +0xdb
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc0000ad000, 0x38, 0xc0000446e0, 0x2, 0x2, 0xc000044780, 0x1, 0x2, 0x101)
        D:/Code/spicetify-cli/src/apply/apply.go:155 +0x9e
github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc00000a8d0, 0x2b, 0xc0000446e0, 0x2, 0x2, 0xc000044780, 0x1, 0x2, 0x101)
        D:/Code/spicetify-cli/src/apply/apply.go:34 +0x484
github.com/khanhas/spicetify-cli/src/cmd.Apply(0x7a52d4, 0x5)
        D:/Code/spicetify-cli/src/cmd/apply.go:73 +0x598
main.main()
        D:/Code/spicetify-cli/spicetify.go:189 +0x519
```

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/60351011/125155274-e760fa80-e15e-11eb-812d-20691883e12c.png)

**Comment by cyacedev** [comment] 2021-07-10 08:09
I'm getting the same error, even when deactivating any custom apps in the config the error still pops up. Interestingly, the Spotify app opens, but doesn't show any content.

**Comment by sinankizar** [comment] 2021-07-10 12:06
I am on the bandwagon too. Did an update to spotify and now it looks like it doesnt contain anything.

**Comment by afonsojramos** [comment] 2021-07-10 12:09
Duplicate of #845.

**Closed by afonsojramos** 2021-07-10 12:10 UTC
Labels: bug

**Comment by ElReyCoraje** [comment] 2021-07-18 19:25
Bro did you fix it ?
