### ISSUE TITLE
Cannot find symbol for Custom app React symbols

### ISSUE THREAD

**Issue by Andrew-Koman** [khanhas/spicetify-cli#884] opened 2021-07-13 00:25 UTC
## ℹ Computer information

- Spotify version: 1.1.63.568
- Spicetify version: 2.5.0

## 📝 Provide detailed reproduction steps (if any)

1. Installed Spotify
2. Launched and logged in to Spotify
3. Closed and and installed Spicetify
4. Ran `Spicetify config` to create a default config file
5. Ran `Spicetify backup apply`
6. The following was what the console spit out

```
spicetify v2.5.0
info spicetify up-to-date
Overwriting themed assets:
OK
Transferring user.css:
OK
Applying additional modifications:
error Cannot find symbol for Custom app React symbols
OK
success Spotify is spiced up!
```

### ✔️ Expected result

It should have applied the default Spicetify theme

### ❌ Actual result

The above output in the terminal, a completely white (and broken) Spotify, shown in the screenshot below. Spicetify seems to have partially applied the defualt theme, but failed partway through, hence the all-white background. If I apply the `Nord-Dark` color scheme, the broken window then shows the background color of that scheme (shown in the second screenshot). The window cannot be dragged, but the buttons work.

To get these questions out of the way, I have reinstalled both Spotify and Spicetify a few times, and `spicetify restore` thankfully can still revert it back to stock Spotify.

Edit: My other laptop automatically ran a Spotify update, and is now having the same issue, so it seems to be some incompatibility with the newest release.

## 📷 Screenshots

![image](https://user-images.githubusercontent.com/35636935/125371686-4be2ac00-e34f-11eb-8f4a-99c2bfd18361.png)
![image](https://user-images.githubusercontent.com/35636935/125371710-57ce6e00-e34f-11eb-84b5-88c2c341d678.png)

**Comment by afonsojramos** [comment] 2021-07-13 03:14
Duplicate of #845

**Closed by afonsojramos** 2021-07-13 03:14 UTC
Labels: bug

**Comment by Andrew-Koman** [comment] 2021-07-15 02:18
> 
> 
> Duplicate of #845

My bad
