### ISSUE TITLE
Lyrics+ CustomApp not working

### ISSUE THREAD

**Issue by znicuuu** [khanhas/spicetify-cli#1089] opened 2021-09-23 14:48 UTC
## ℹ Computer information

- Spotify version: 1.1.68.632.g2b11de83
- Spicetify version: 2.6.4

### ✔️ Expected result
Lyrics+ and Lyrics+ config showing up normally

### ❌ Actual result
Lyrics+ giving an error and the Lyrics+ config also not showing up

## 📷 Screenshots
![image](https://user-images.githubusercontent.com/73033465/134529081-501ca097-56f6-46bf-8dc9-837b72f459d0.png)

**Comment by TheGeeKing** [comment] 2021-09-23 19:05
Duplicate of #1088

**Closed** 2021-09-24 09:17 UTC
Labels: bug
