### ISSUE TITLE
New releases customapp breaks spotify

### ISSUE THREAD

**Issue by Jusp3** [khanhas/spicetify-cli#977] opened 2021-08-18 13:28 UTC
## ℹ Computer information

- Spotify version: 1.1.66.578.gc54d0f69-a
- Spicetify version:  2.6.0

## 📝 Provide detailed reproduction steps (if any)

1. … Apply with new releases custom app
2. …
3. …

### ✔️ Expected result

Spotify launch and works fine with new releases.

### ❌ Actual result

Spotify launches but everything is blank.

## 📷 Screenshots
![Spotify_xht6ERrRHt 1](https://user-images.githubusercontent.com/75336354/129906463-654b7c64-ee8a-491e-8d5f-0de4d6e98497.png)

**Comment by edo2313** [comment] 2021-08-19 01:04
Duplicate of #845

**Comment by afonsojramos** [comment] 2021-08-19 13:01
Customapps are not quite working at the moment, we're aware of this issue.

**Comment by TheGeeKing** [comment] 2021-08-30 08:57
I post here so maybe people will look before posting a duplicate issue

If on you are on Windows :
1. Block updates :
del %localappdata%\Spotify\Update

mkdir %localappdata%\Spotify\Update

icacls %localappdata%\Spotify\Update /deny "%username%":D

icacls %localappdata%\Spotify\Update /deny "%username%":R

2. Rollback to 1.1.65.643 :
https://www.filepuma.com/download/spotify_1.1.65.643-29529/


For Mac users :
1. Block updates :
     1. In the Application folder, right-click on the Spotify app and choose 'Get Info'

     2. in the 'Get info' window, make sure you check 'Locked', right at the top.  

2. Rollback to 1.1.59.714 (maybe newer versions work but I don't know so say it if you could try it) :
https://www.filepuma.com/download/spotify_1.1.59.714-28782/

@Jusp3 don't know if you should close this issue, but you have all information above.

A new version of spicetify will be released but not soon.

For further help :
Join the discord : https://discord.gg/VnevqPp2Rr
And ping me : TheGeeKing#7841

**Closed** 2021-08-30 19:20 UTC
Labels: bug
