### ISSUE TITLE
Not able to view/access charts.

### ISSUE THREAD

**Issue by fosam** [khanhas/spicetify-cli#841] opened 2021-07-06 19:46 UTC
## ℹ Computer information

- Spotify version: 1.1.62.583.gdac868ed-a
- Spicetify version: 250

## 📝 Provide detailed reproduction steps (if any)

1. Search
2. Charts

### ✔️ Expected result

Be able to see/access the charts.

### ❌ Actual result

The actual result is the same as in the home screen, meaning seeing things like "more of what you like" "more like..." "suggested artists" etc...

## 📷 Screenshots

![Capture 06_07_2021_21_40_27](https://user-images.githubusercontent.com/52612348/124657845-4e528b00-dea3-11eb-83bc-66d43b38b107.png)

![Capture 06_07_2021_21_34_17](https://user-images.githubusercontent.com/52612348/124657860-53173f00-dea3-11eb-8305-69617418f76b.png)

**Comment by RhapsodySL** [comment] 2021-07-07 21:36
Duplicate of https://github.com/khanhas/spicetify-cli/issues/820

**Closed** 2021-07-08 12:50 UTC
Labels: bug
