### ISSUE TITLE
Experimental features missing

### ISSUE THREAD

**Issue by fosam** [khanhas/spicetify-cli#1438] opened 2022-01-30 18:57 UTC
## ℹ Computer information

- Spotify version: 1.1.77
- Spicetify version: v2.8.5

## 📝 Provide detailed reproduction steps (if any)

Click on your profile menu and choose experimental features

### ✔️ Expected result

See experimental features menu.

### ❌ Actual result

Menu is missing.

## 📷 Screenshots

<details>
<summary>Here</summary>
<img src=https://user-images.githubusercontent.com/52612348/151713362-b2033ad2-92b8-46fd-9160-075ed5e31989.png>
</details>

In v2.8.4 this did not happen

**Comment by sagars007** [comment] 2022-01-30 20:04
Known issue in v2.8.4 https://github.com/khanhas/spicetify-cli/issues/1417
I also had the same issue in v2.8.4. It's fixed in v2.8.5

**Comment by fosam** [comment] 2022-01-30 21:51
You probably mean the opposite?

<details>
<summary>v2.8.4</summary>
<img src=https://user-images.githubusercontent.com/52612348/151719231-5edee394-542f-4ee0-bf0f-4a42abceeafb.png>
</details>

<details>
<summary>v2.8.5</summary>
<img src=https://user-images.githubusercontent.com/52612348/151713362-b2033ad2-92b8-46fd-9160-075ed5e31989.png>
</details>

Will anyway keep 284 at the moment.

**Comment by afonsojramos** [comment] 2022-01-30 23:48
It will depend on which version of Spotify you have I'd say

**Comment by fosam** [comment] 2022-01-31 00:24
I stated that i have 1.1.77 which i tried with both 284 and 285, but as i said, experimental features are missing only from 285 so there must be something with that version.

**Comment by sagars007** [comment] 2022-01-31 07:14
> 

Nope I had the same issue as reported earlier: https://github.com/khanhas/spicetify-cli/issues/1417
Spotify version: 1.1.77.643
Spicetify version: 2.8.4

I'm currently using: 
Spotify version: 1.1.77.643
Spicetify version: 2.8.5

Works fine for me.
 
![spicetify-info](https://user-images.githubusercontent.com/56472130/151752691-6cb11054-8951-4992-bd63-5a05af394706.png)

**Comment by fosam** [comment] 2022-01-31 21:53
This is strange, how do we solve this issue? just stay on 284?

**Comment by afonsojramos** [comment] 2022-02-01 00:00
This is probably related to #1419. I will try to investigate soon!

**Comment by jeroentvb** [comment] 2022-02-01 07:50
Also works for me on spotify v1.1.77 and spicetify v2.8.5.

@fosam could you do the following steps to gather some additional information?
1. Enable devtools `spicetify enable-devtool`
2. Open the console (right click anywhere > inspect element > console tab)
3. Open the experimental features dialog
4. Make a screenshot of the console, and post it here

**Comment by fosam** [comment] 2022-02-01 13:34
When i open the experimental features dialog (step.3) nothing changes in the console, it stays the same as when i opened it.

<details>
<summary>Console</summary>
<img src=https://user-images.githubusercontent.com/52612348/151977360-a87af326-9938-4363-a906-7e7204cb7b01.png>
</details>

**Comment by jeroentvb** [comment] 2022-02-04 11:55
I've tested in both macOs Big Sur and Windows 10 with spotify 1.1.77 and spicetify 2.8.5 and can't seem to reproduce the issue.
So I'm unable to fix this issue.

**Comment by afonsojramos** [comment] 2022-02-04 12:18
I actually had the issue too, but now it is fixed?? 🤷 Can you do a new spicetify apply @fosam?

**Comment by fosam** [comment] 2022-02-04 13:06
I did it just now, and the features are still missing, how come yours is fixed, @afonsojramos?

**Comment by fosam** [comment] 2022-02-04 23:44
Guys, i found the cause of this issue on my side, i had an old xpui folder (from 1.1.70) which i modified some months ago, (which also didn't cause any issues until after v2.8.4) and when i completely reinstalled Spotify, i got a fresh xpui folder which seems to be working now with the recent versions, v2.9.0 included.

I assume my old xpui folder had some old element names which were not compatible with Spicetify v2.8.5 and later?

**Comment by fosam** [comment] 2022-02-04 23:45
Guys, i found the cause of this issue on my side, i had an old xpui folder (from 1.1.70) which i modified some months ago, (which also didn't cause any issues until after v2.8.4) and when i completely reinstalled Spotify, i got a fresh xpui folder which seems to be working now with the recent versions, v2.9.0 included.

I assume my old xpui folder had some old element names which were not compatible with Spicetify v2.8.5 and later?

Apologies since it was my fault.

**Comment by afonsojramos** [comment] 2022-02-06 20:04
Awesome to see it fixed either way! Will close the issue now.

**Closed by afonsojramos** 2022-02-06 20:04 UTC
Labels: 🐛 bug
