### ISSUE TITLE
New Release crash

### ISSUE THREAD

**Issue by vanja-san** [khanhas/spicetify-cli#1009] opened 2021-08-30 08:36 UTC
## ℹ Computer information

- Spotify version: 1.1.66.580
- Spicetify version: 2.6.0

## 📝 Provide detailed reproduction steps (if any)

1. Install Custom App «New Release»
2. Open Spotify

### ✔️ Expected result

Successful opening of Spotify

### ❌ Actual result

Error when opening Spotify =>

## 📷 Screenshots
I'm sorry it's in Russian.
```
(Pop-up window)
Something went wrong
Update page
(Button) Update
```
![изображение](https://user-images.githubusercontent.com/7201687/131310908-ea3a51f9-06c1-4cd9-b675-bab9283159ad.png)

**Comment by TheGeeKing** [comment] 2021-08-30 08:39
Duplicate of #977
If you are on Windows :

Block auto update :
del %localappdata%\Spotify\Update

mkdir %localappdata%\Spotify\Update

icacls %localappdata%\Spotify\Update /deny "%username%":D

icacls %localappdata%\Spotify\Update /deny "%username%":R

Rollback to 1.1.65.643 : https://www.filepuma.com/download/spotify_1.1.65.643-29529/

**Closed** 2021-08-31 11:43 UTC
Labels: bug
