### ISSUE TITLE
Unable to apply

### ISSUE THREAD

**Issue by applekillerbyjames** [khanhas/spicetify-cli#854] opened 2021-07-08 21:54 UTC
## ℹ Computer information

- Spotify version: 1.1.63.568.gda8cb5ac-a
- Spicetify version:  2.5.0

## 📝 Provide detailed reproduction steps (if any)

1.run spicetify apply
2. …
3. …

### ✔️ Expected result

_What is the expected result of the above steps?_
Spicetify applies theme
### ❌ Actual result

_What is the actual result of the above steps?_
Spicetify gives error
goroutine 1 [running]:
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp.func1(0xc000894000, 0x1aaab5, 0x1aaab5, 0xc000894000)
	D:/Code/spicetify-cli/src/apply/apply.go:180 +0xd86
github.com/khanhas/spicetify-cli/src/utils.ModifyFile(0xc0000149c0, 0x3e, 0xc0000c19d8)
	D:/Code/spicetify-cli/src/utils/utils.go:190 +0xd8
github.com/khanhas/spicetify-cli/src/apply.insertCustomApp(0xc0000149c0, 0x3e, 0xc000070100, 0x5, 0x8, 0xc0000100c0, 0x2, 0x2, 0x101)
	D:/Code/spicetify-cli/src/apply/apply.go:155 +0x97
github.com/khanhas/spicetify-cli/src/apply.AdditionalOptions(0xc0000142c0, 0x31, 0xc000070100, 0x5, 0x8, 0xc0000100c0, 0x2, 0x2, 0x101)
	D:/Code/spicetify-cli/src/apply/apply.go:34 +0x466
github.com/khanhas/spicetify-cli/src/cmd.Apply(0x13a5a94, 0x5)
	D:/Code/spicetify-cli/src/cmd/apply.go:73 +0x58c
main.main()
	D:/Code/spicetify-cli/spicetify.go:189 +0x4f9
## 📷 Screenshots

_Are there any useful screenshots?_

**Comment by eetle** [comment] 2021-07-09 08:51
I've got the exact same issue (on windows 11), after a fresh install of  spicetify-cli I get this new error 

Applying additional modifications:
error Cannot find symbol for Custom app React symbols
OK
success Spotify is spiced up!

And when I open up Spotify I just get the white screen.
Its probably just some issue with the new Spotify update.

**Comment by ImCheesecake** [comment] 2021-07-09 09:19
I get the same problem, also on windows 11

![image](https://user-images.githubusercontent.com/43030367/125055465-81fe0280-e0a7-11eb-85f4-ebb6ed67b739.png)

**Comment by Vismay23** [comment] 2021-07-09 10:39
facing the same issue

**Comment by afonsojramos** [comment] 2021-07-09 11:03
For now Windows 11 is not a supported platform yet.

**Comment by grasonchan** [comment] 2021-07-09 11:09
> For now Windows 11 is not a supported platform yet.

macOS Big Sur have the same issus.

**Comment by afonsojramos** [comment] 2021-07-09 11:32
However, it's a duplicate of #845.

**Closed by afonsojramos** 2021-07-09 11:32 UTC
Labels: bug
